### ISSUE TITLE
Constructing sequence phase impedance model from Z0,Z1 

### ISSUE THREAD

**Issue by frederikgeth** [lanl-ansi/ThreePhasePowerModels.jl#42]
A colleague and I have been experimenting with parsing an OpenDSS case study that he developed a while back. It uses linecodes with impedance defined by Z0 and Z1. We noticed a few things. 

Even if Z0 and Z1 are defined in the OpenDSS format, they are not actually used. It seems that the line impedance definition eq (22) / (23) in [1] is missing and that instead the default OpenDSS line impedance values are used.

Some minor bugs:
- the lengths (and the length units) are not used in the calculation of the branch impedance [here](https://github.com/lanl-ansi/ThreePhasePowerModels.jl/blob/master/src/io/opendss.jl#L1068)
- we had to comment out [this](https://github.com/lanl-ansi/ThreePhasePowerModels.jl/blob/master/src/io/opendss.jl#L1326) line to parse the case.

Hopefully I can do a PR next week to fix some of these bugs, but I haven't checked yet what will be updated anyway by https://github.com/lanl-ansi/ThreePhasePowerModels.jl/pull/36

[1] Kersting, W. H., & Philips, W. H. (1995). Distribution feeder line models. IEEE Trans. Ind. Appl., 31(4), 715–720.

**Comment by pseudocubic** [comment]
This should be covered by PR #36 which should be merged soon

**Comment by pseudocubic** [comment]
I looked closer at this, and Z0, Z1 on linecodes is not valid OpenDSS. There are components that do support Z0, Z1, which is why I thought this case would be covered in PR #36, such as Reactors. 

The proper way to do this would be to pass r0, x0, r1, x1 separately. I don't think we should be supporting features that do not appear in OpenDSS, and instead assert that users either rewrite their OpenDSS files to be valid, or write their own function to parse the special cases they have created.

You are correct that lengths (and their units) are not yet used. At present we are standardized around the OpenDSS defaults, `units="none"` and `length=1`. This feature will be added at a future date.

**Comment by frederikgeth** [comment]
Sorry, I didn't explain myself well. I don't want support for features that are not in the manual. I refer to the case where the OpenDSS file includes R0, R1, X0 and X1 which should then used as Z0, Z1 in the matrix in eq (23) in [1] to determine the impedance matrix. It seems that the latter part seems to be missing.

**Comment by pseudocubic** [comment]
Ah, okay. That indeed should be supported by PR #36 (now in master branch), but it is not thoroughly unit tested yet, so let me know if you find any errors with that.

**Comment by frederikgeth** [comment]
Awesome! Will do. Thx
